esphome:
  name: espnow-battery-1
  platform: ESP32
  board: esp32dev

external_components:
  - source: github://yourusername/espnow-mesh
    components: [espnow_mesh]

wifi: {}

logger:

espnow_mesh:
  id: mesh
  node_id: "batt1"
  encryption_key: "mysecretkey12345"

sensor:
  - platform: dht
    pin: GPIO4
    model: DHT22
    temperature:
      id: temp_sensor
    humidity:
      id: humid_sensor
    update_interval: 1s
  - platform: adc
    pin: GPIO34
    id: battery_sensor
    filters:
      - multiply: 100

substitutions:
  send_interval: "1000ms"

script:
  - id: send_data
    mode: restart
    then:
      - lambda: |-
          char buffer[50];
          sprintf(buffer, "%.1f:%.1f", id(temp_sensor).state, id(battery_sensor).state);
          id(mesh).send_message(buffer);
      - delay: ${send_interval}
