esphome:
  name: router-node
  platform: ESP32
  board: esp32dev

external_components:
  - source: github://codegraffiti/espnow-mesh@v2
    components: [espnow_mesh]

logger:

espnow_mesh:
  role: router

switch:
  - platform: gpio
    pin: GPIO5
    name: "Relay 1"
  - platform: gpio
    pin: GPIO18
    name: "Relay 2"
  - platform: modbus
    id: modbus_switch1
    register_type: coil
    address: 1
    name: "Modbus Switch 1"
  - platform: modbus
    id: modbus_switch2
    register_type: coil
    address: 2
    name: "Modbus Switch 2"

sensor:
  - platform: dht
    pin: GPIO4
    model: DHT22
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s
  - platform: adc
    pin: GPIO33
    name: "Light Level"
    update_interval: 60s

modbus:
  id: modbus1
  uart_num: 1
  tx_pin: GPIO17
  rx_pin: GPIO16
